---
- hosts: databases
  tasks:
  - name: create a file if doesnt exist
    file:
      state: touch
      path: /home/ansible/hostname.conf
  - name: create file if it doesnt exist
    lineinfile: 
      state: present 
      dest: /home/ansible/hostname.conf     
      line: Hostname={{ ansible_hostname }}


