---
- hosts: all
  become: yes
  tasks:
  - name: Install Apache
    yum: 
      name: httpd
      state: latest
  - name: create a file if doesnt exist
    file:
      state: touch
      path: /var/www/html/index.html
  - name: create file if it doesnt exist
    lineinfile: 
      state: present 
      dest: /var/www/html/index.html     
      line: Hostname={{ ansible_hostname }}
  - name: restart apache
    service:
      name: httpd
      state: reloaded
      enabled: yes



