---
- hosts: databases
  tasks: 
  - name: upload a file if it doesnt exist
    copy: 
     src: /opt/pragram1.sh
     dest: /home/ansible/program1.sh
     mode: 0755
  - name: if line not there add it
    lineinfile: 
     state: present
     dest: /home/ansible/pragram1.sh
     regexp: '^HOSTNAME='
     line: HOSTNAME={{ansible_hostname}}
  - name: Run the program
    shell: /home/ansible/program1.sh
    register: program_output
  - debug: msg="stdout={{program_output}}" 
