- name: Create a file if it doesnt exist
  file: state=touch path=/var/www/html/index.html
- name: If hostname not there add it
  lineinfile:
    state: present 
    dest: /var/www/html/index.html
    line: Hostname={{ansible_hostname}}
